from __future__ import annotations

from app import banco


def test_dsn_aceita_database_url(monkeypatch) -> None:
    monkeypatch.setenv("DATABASE_URL", "postgres://usuario:senha@db:5432/acervo")
    assert banco.dsn() == "postgresql://usuario:senha@db:5432/acervo"


def test_adaptador_converte_marcadores_e_top() -> None:
    sql = banco._adaptar_sql("SELECT TOP 5 id FROM casos WHERE categoria = ?")
    assert sql == "SELECT id FROM casos WHERE categoria = %s LIMIT 5"


def test_adaptador_converte_ddl_legado() -> None:
    sql = banco._adaptar_sql(
        "IF OBJECT_ID('dbo.exemplo') IS NULL\n"
        "CREATE TABLE dbo.exemplo (id int IDENTITY(1,1), corpo nvarchar(max))"
    )
    assert sql.startswith("CREATE TABLE IF NOT EXISTS dbo.exemplo")
    assert "GENERATED BY DEFAULT AS IDENTITY" in sql
    assert "corpo text" in sql


def test_tabelas_usam_nome_sem_prefixo() -> None:
    assert banco.PREFIXO == ""
    assert banco._qualificar("SELECT * FROM casos") == "SELECT * FROM dbo.casos"
    assert "casos" in banco.TABELAS_COM_PREFIXO_LEGADO
