-- Entidade canônica de pessoas e seus papéis nos casos.
-- PostgreSQL, schema operacional atual: dbo.
--
-- Este arquivo é somente DDL e pode ser executado mais de uma vez. O backfill
-- está separado em 005_pessoas_backfill.sql.

BEGIN;

CREATE SCHEMA IF NOT EXISTS dbo;

CREATE TABLE IF NOT EXISTS dbo.pessoas (
    id                bigint GENERATED BY DEFAULT AS IDENTITY
                              CONSTRAINT pk_pessoas PRIMARY KEY,
    cpf               varchar(11),
    nome              varchar(200) NOT NULL,
    criado_em         timestamptz NOT NULL DEFAULT now(),
    atualizado_em     timestamptz NOT NULL DEFAULT now(),
    criado_por        varchar(200),
    atualizado_por    varchar(200),
    CONSTRAINT uq_pessoas_cpf UNIQUE (cpf),
    CONSTRAINT ck_pessoas_nome_nao_vazio CHECK (btrim(nome) <> ''),
    CONSTRAINT ck_pessoas_cpf_formato CHECK (cpf IS NULL OR cpf ~ '^[0-9]{11}$')
);

CREATE TABLE IF NOT EXISTS dbo.caso_pessoas (
    caso_id           varchar(64) NOT NULL,
    pessoa_id         bigint NOT NULL,
    papel             varchar(60) NOT NULL,
    criado_em         timestamptz NOT NULL DEFAULT now(),
    criado_por        varchar(200),
    CONSTRAINT pk_caso_pessoas PRIMARY KEY (caso_id, pessoa_id, papel),
    CONSTRAINT fk_caso_pessoas_caso FOREIGN KEY (caso_id)
        REFERENCES dbo.casos (id) ON DELETE CASCADE,
    CONSTRAINT fk_caso_pessoas_pessoa FOREIGN KEY (pessoa_id)
        REFERENCES dbo.pessoas (id) ON DELETE RESTRICT,
    CONSTRAINT ck_caso_pessoas_papel CHECK (btrim(papel) <> '')
);

-- Um caso pode ter várias pessoas e papéis, mas apenas um cliente principal.
CREATE UNIQUE INDEX IF NOT EXISTS uq_caso_pessoas_cliente_principal
    ON dbo.caso_pessoas (caso_id)
    WHERE papel = 'cliente_principal';

CREATE INDEX IF NOT EXISTS ix_caso_pessoas_pessoa
    ON dbo.caso_pessoas (pessoa_id, caso_id);

-- Pendências que o backfill se recusa a resolver por palpite.
CREATE TABLE IF NOT EXISTS dbo.pessoas_revisao (
    id                bigint GENERATED BY DEFAULT AS IDENTITY
                              CONSTRAINT pk_pessoas_revisao PRIMARY KEY,
    caso_id           varchar(64) NOT NULL,
    motivo            varchar(80) NOT NULL,
    nome_encontrado   varchar(200),
    cpfs_encontrados  jsonb NOT NULL DEFAULT '[]'::jsonb,
    detalhes          jsonb NOT NULL DEFAULT '{}'::jsonb,
    criado_em         timestamptz NOT NULL DEFAULT now(),
    atualizado_em     timestamptz NOT NULL DEFAULT now(),
    resolvido_em      timestamptz,
    resolvido_por     varchar(200),
    CONSTRAINT uq_pessoas_revisao_caso_motivo UNIQUE (caso_id, motivo),
    CONSTRAINT fk_pessoas_revisao_caso FOREIGN KEY (caso_id)
        REFERENCES dbo.casos (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_pessoas_revisao_pendentes
    ON dbo.pessoas_revisao (motivo, criado_em)
    WHERE resolvido_em IS NULL;

-- Compatibilidade durante a transição: a aplicação pode passar a ler desta
-- view antes de deixar de escrever em casos.cliente.
CREATE OR REPLACE VIEW dbo.vw_caso_cliente AS
SELECT
    c.id AS caso_id,
    p.id AS pessoa_id,
    p.nome,
    p.cpf,
    cp.papel
FROM dbo.casos AS c
LEFT JOIN dbo.caso_pessoas AS cp
       ON cp.caso_id = c.id
      AND cp.papel = 'cliente_principal'
LEFT JOIN dbo.pessoas AS p
       ON p.id = cp.pessoa_id;

COMMENT ON TABLE dbo.pessoas IS
    'Cadastro canônico de pessoas; o CPF extraído dos documentos permanece como evidência bruta.';
COMMENT ON TABLE dbo.caso_pessoas IS
    'Papéis exercidos por pessoas em cada caso; suporta titular, dependente, empregador e testemunha.';
COMMENT ON TABLE dbo.pessoas_revisao IS
    'Conflitos que não podem ser resolvidos automaticamente sem risco de vincular pessoas erradas.';

COMMIT;
